spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/password
    username: password
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
#    this is for convenient communication in the console
#    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect